name: Build and deploy an app to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  CONTAINER_NAME: "test"
  RESOURCE_GROUP: "rg-desarrollo-aks"
  CLUSTER_NAME: "aks-desarrollo-cluster"
  DEPLOYMENT_MANIFEST_PATH: "your-deployment-manifest-path"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Builds and pushes an image to Docker Hub
      - name: Build and push image to Docker Hub
        run: |
          docker build -t ${{ env.CONTAINER_NAME }}:${{ github.sha }} .
          docker tag ${{ env.CONTAINER_NAME }}:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}

  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [buildImage]
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Rest of your deployment steps using the Docker image from Docker Hub
      # ...
